@extends('layout.app')
@section('title','Privacy')

@section('content')
<div class="container-fluid">
    <div class="container mt-4">
        <h3 class="fw-bold text-center">
            “Privacy Centre” Privacy Notice
        </h3>
        <p class="fst-italic fw-medium text-center">
            Last Updated August 2024
        </p>

        <p class="text-center fw-medium">
            Welcome to (“Privacy Centre” “We” “Us” “Our”).
        </p>

        <p class="fw-medium">
            Privacy Centre is Privacy handling firm based on privacy and personal data protection services; We assist
            you to
            become the privacy and personal data protection compliant in United Republic of Tanzania and globally. We
            are
            dedicated to assist your business in mitigating the consequences of non-compliance on privacy such as
            avoiding
            reputational damage and penalties, Privacy policy designing, research, and general privacy compliance
            advisory.
            While on our website, we process data about you and your device. This notice explains how we handle your
            data
            and our attitude towards data protection.
        </p>
        <p class="fs-5 fw-bold">
            Summary
        </p>
        <p class="fw-medium">
            We only retain what is necessary and delete it when it is no longer necessary. We will be lying to you if we
            say
            we do not use your data. We do! But it is to provide services to you, to fulfil our legal obligation, to
            respond
            to your inquiries, and to manage our relationship with you. The law affords you lots of data protection
            rights,
            and you may choose to contact us at any time to exercise them.
        </p>

        <p class="fs-5 fw-bold">
            The data we hold about you
        </p>
        <p class="fw-medium">
            We use your data to provide services to you, fulfil our legal obligations, respond to your inquiries,
            provide
            customer support, improve our services, and manage our relationship with you.
        </p>
        <ul class="fw-medium">
            <li>
                Your name and contact information
            </li>
            <li>
                Information about your business activities with us
            </li>
            <li>
                Information about your enquiries and our dealings
            </li>
            <li>
                Data from contracts, including details of the contract, third-party providers, counterparty names and
                email addresses, comments, activity on contracts, and signatures
            </li>
        </ul>
        <p class="fw-medium">
            If you are a client, we collect:

        </p>
        <h5 class="fw-bold">
            Client
        </h5>
        <p class="fw-medium">
            If you are a prospective client, we collect:
        </p>
        <ul class="fw-medium">
            <li>
                Your name and contact information
            </li>
            <li>
                Information about your business activities with us
            </li>
            <li>
                Information about your enquiries and our dealings
            </li>

        </ul>

        <h5 class="fw-bold">
            Prospective Client
        </h5>
        <p class="fw-medium">
            If you visit our website, it is a pleasure to have you here. We process log files generated by servers,
            which
            include the IP address assigned to you. If you do not want us to process your log file, our website is
            accessible via Tor.
        </p>

        <h5 class="fw-bold">
            Site Visitor
        </h5>
        <p class="fw-medium">
            If you subscribe to our newsletter, join our <span class="fw-bold">Privacy Centre</span> community, or
            register for any of our webinars,
            trainings or workshops:
            we collect:
        </p>
        <ul class="fw-medium">
            <li>
                Your name (you do not have to give us your real name)
            </li>
            <li>
                Your email address or other means of contact accessible to you

            </li>
        </ul>

        <h5 class="fw-bold">
            Subscription and Community Engagement
        </h5>
        <h5 class="fw-bold">
            What we do with the data
        </h5>
        <p class="fw-medium">
            Our communications with you are purposeful and based on your relationship with us. If you are a client, our
            communication aims to fulfil contractual obligations and ensure satisfaction. As a prospective client, we
            reach
            out to respond to your queries and showcase our offerings. Newsletter subscribers and <span
                class="fw-bold">Privacy Centre</span>
            community
            members receive bimonthly updates with the option to unsubscribe anytime. Registrants for webinars receive
            only
            the essential event details.
        </p>
        <p class="fw-medium">
            If you are a client, we contact you only to fulfil our contractual obligations to you and ensure your
            satisfaction.
        </p>
        <h5 class="fw-bold">
            Client
        </h5>
        <p class="fw-medium">
            If you are a prospective client, we will contact you to respond to your enquiries and share information on
            the
            services we can provide you with.
        </p>
        <h5 class="fw-bold">
            Prospective Client
        </h5>
        <p class="fw-medium">
            If you subscribe to our <span class="fw-bold">Privacy Centre</span> Alert, or join our <span
                class="fw-bold">Privacy Centre</span> community, we will only contact you to
            share an update. We promise not to send you updates more than twice in a month. You may unsubscribe from the
            newsletter at any time through the unsubscribe button at the end of the email or on LinkedIn for Privacy
            Centre.

        </p>
        <h5 class="fw-bold">
            Subscription and Community Engagement
        </h5>
        <p class="fw-medium">
            If you register for any of our webinars, we will only contact you to send you details about the event.
        </p>
        <h5 class="fw-bold">
            Webinars
        </h5>
        <h5 class="fw-bold">
            Purpose of processing your data and the lawful basis
        </h5>
        <p class="fw-medium">
            We rely on an appropriate lawful basis determined by our privacy team and documented in accordance with the
            extant data protection laws. In appropriate circumstances, we rely on the performance of contracts, legal
            obligations, our legitimate interests, and consent when it is appropriate.
        </p>
        <p class="fw-medium">
            If we have to use consent as a lawful basis, we will provide you with a consent request. You have the right
            to
            refuse consent or withdraw your consent at any time by contacting us at e-mail:
            <a href="mailto:privacycentre@gmail.com">privacycentre@gmail.com</a> or unsubscribing from our services.
            However, we should mention that consent withdrawal
            will not affect the lawfulness of any processing carried out before you withdraw your consent.
        </p>
        <p class="fw-medium">
            The table below shows why we process your personal data and on what basis:
        </p>
        <h5 class="fw-bold">
            PURPOSE OF PROCESSING LAWFUL BASIS
        </h5>
        <ul class="fw-medium">
            <li>
                Delivering, developing and improving our website
            </li>
            <li>
                Enabling us to enhance, customise or modify our services and communication
            </li>
            <li>
                Prevention of fraud and security
            </li>
        </ul>
        <h5 class="fw-bold">
            Legitimate Interest
        </h5>
        <ul class="fw-medium">
            <li>
                To provide our services to you
            </li>
            <li>
                To respond to your enquiries
            </li>
            <li>
                To communicate with you
            </li>
            <li>
                To inform you whenever there are changes to our services

            </li>

        </ul>
        <h5 class="fw-bold">
            Contract
        </h5>
        <ul class="fw-medium">
            <li>
                Share newsletter updates with you
            </li>
            <li>
                Share details to join our events
            </li>
            <li>
                To share Tech Policy Updates, Privacy in Africa newsletter, and alerts with members of our community
            </li>
        </ul>
        <h5 class="fw-bold">
            Consent
        </h5>
        <ul>
            <li class="fw-medium">
                To fulfil requests required by law
                Legal obligation
            </li>
        </ul>
        <h5 class="fw-bold">
            Transfer of Data outside United Republic of Tanzania
        </h5>
        <p class="fw-medium">
            We rely on the appropriate data transfer mechanism or any of its relevant exceptions to transfer data
            outside
            mentioned Country boundary. We would ensure appropriate safeguards before transferring data outside United
            Republic of Tanzania, which include countries whitelisted by the United Republic of Tanzania regulator, and
            performance of contract. You can reach out to us to verify the safeguards we have in place.

        </p>
        <h5 class="fw-bold">
            Your rights
        </h5>
        <p class="fw-medium">
            You possess rights regarding your data, including access to your personal information and the ability to
            request
            its erasure or correction if inaccurate or incomplete. You can object to our processing of your data for
            marketing communications like newsletters or event notifications. If unsatisfied, you also have the right to
            lodge complaints with the relevant supervisory authority or seek legal remedies.
            You have loads of data protection rights, and we respect them. They include:
        </p>
        <ul class="fw-medium">
            <li>
                Right to tell us to allow you access your personal data;
            </li>
            <li>
                Right to ask us to erase or delete your data;
            </li>
            <li>Right to request that we correct your data when it is inaccurate or incomplete;</li>
            <li> Right to object to our processing or use of your data for purposes such as sending you our captivating
                newsletters or information about our exceptional events; and</li>
            <li>The right to complain to the supervisory authority or even go to court. And you can go as far as the
                Supreme
                Court.</li>
        </ul>
        <h5 class="fw-bold">
            Third parties
        </h5>
        <p class="fw-medium">
            Generally, we guard data jealously because we do not like to share. Our website has third-party requests.
            They
            do not process your data. However, where relevant, we share your data with third parties if:
        </p>
        <ul class="fw-medium">
            <li>
                If we have to complete a contract on your behalf;
            </li>
            <li>
                If you give your explicit consent;
            </li>
            <li>
                If there is a legal obligation on us to share such data under existing laws and regulations; and
            </li>
            <li>
                There is a court judgement, injunction, or other binding legal directive.
            </li>
        </ul>

        <h5 class="fw-bold">
            Cookies
        </h5>
        <p class="fw-medium">
            We do not use cookies on our website. The only cookies we have to offer you are chocolate double-chip.
            How long do we store your data?
            We retain your data for the duration of our relationship. However, we will also retain data, subject to the
            relevant provisions of applicable laws.
        </p>
        <h5 class="fw-bold">
            Security of Data
        </h5>
        <p class="fw-medium">
            We are very particular about preserving and protecting your data. Therefore, to avoid the loss, theft,
            misuse,
            unauthorised access, disclosure, alteration, and destruction of your information, we have put in place a
            range
            of administrative, technical, organisational, and physical safeguards. Despite this, we cannot completely
            guarantee the security of any information transmitted, nonetheless, we do our best to ensure security of
            data.
        </p>
        <h5 class="fw-bold">
            Changes to our Privacy Notice
        </h5>
        <p class="fw-medium">
            We will continually assess our data protection practices to ensure that your rights are guaranteed. To this
            end,
            we may amend this privacy notice at any time. In the event that changes are made, we will either indicate at
            the
            top of this privacy notice when it was most recently updated or send you a notification that the notice has
            been
            updated. Please be assured that we will not use any previously collected personal data, to the extent that
            it is
            not collected under the new privacy policy, in a manner materially different from that represented at the
            time
            it was collected.
        </p>

        <p class="fw-medium">
            E-mail: <a href="mailto:privacycentre@gmail.com ">privacycentre@gmail.com </a>.
        </p>


    </div>
    <div class="row btn-teal">
        <x-footer-component />
    </div>
</div>
@endsection